export const origins = [
  "East Blue",
  "West Blue",
  "North Blue",
  "South Blue",
  "Grand Line",
  "Red Line",
  "Skypiea",
  "Wano Kuni",
  "Water 7",
  "Alabasta",
  "Dressrosa",
  "Sabaody",
  "Punk Hazard",
  "Egghead",
  "Whole Cake Island",
  "Zou",
  "Fishman Island",
  "Elbaf",
];

export const devilFruits = [
  "Fruit du Caoutchoutier (Gomu Gomu no Mi)",
  "Fruit du Feu (Mera Mera no Mi)",
  "Fruit de la Glace (Hie Hie no Mi)",
  "Fruit du Séisme (Gura Gura no Mi)",
  "Fruit des Ténèbres (Yami Yami no Mi)",
  "Fruit de l’Opération (Ope Ope no Mi)",
  "Fruit du Mochi (Mochi Mochi no Mi)",
  "Fruit des Âmes (Soru Soru no Mi)",
  "Fruit des Fils (Ito Ito no Mi)",
  "Fruit du Phénix (Tori Tori no Mi : Modèle Phénix)",
  "Fruit du Dragon Azur (Uo Uo no Mi : Modèle Seiryu)",
  "Fruit du Dieu Soleil (Nika Nika no Mi)",
  "Fruit du Bouddha (Hito Hito no Mi : Modèle Daibutsu)",
  "Fruit de la Barrière (Bari Bari no Mi)",
  "Fruit de la Bombe (Bomu Bomu no Mi)",
  "Fruit du Grignotage (Baku Baku no Mi)",
  "Fruit de la Copie (Mane Mane no Mi)",
  "Fruit du Poison (Doku Doku no Mi)",
  "Fruit de l’Ombre (Kage Kage no Mi)",
];

export const statsLevels = {
  cerveauLevels: [
    { text: "Génie absolu", value: 10 },
    { text: "Génie stratégique", value: 9 },
    { text: "Très intelligent", value: 8 },
    { text: "Intelligent", value: 7 },
    { text: "Moyennement malin", value: 6 },
    { text: "Pas très malin", value: 5 },
    { text: "Pas futé", value: 4 },
    { text: "Vraiment bête", value: 3 },
    { text: "Complètement à l’ouest", value: 2 },
    { text: "Esprit absent", value: 1 },
  ],

  vitesseLevels: [
    { text: "Omniprésence instantanée", value: 10 },
    { text: "Téléportation", value: 9 },
    { text: "Vitesse de la lumière", value: 8 },
    { text: "Ultra rapide", value: 7 },
    { text: "Très rapide", value: 6 },
    { text: "Rapide", value: 5 },
    { text: "Moyen", value: 4 },
    { text: "Lent", value: 3 },
    { text: "Vraiment lent", value: 2 },
    { text: "Se traîne péniblement", value: 1 },
  ],

  forceLevels: [
    { text: "Force divine", value: 10 },
    { text: "Force surhumaine", value: 9 },
    { text: "Force titanesque", value: 8 },
    { text: "Force colossale", value: 7 },
    { text: "Très fort", value: 6 },
    { text: "Fort", value: 5 },
    { text: "Moyenne", value: 4 },
    { text: "Faible", value: 3 },
    { text: "Très faible", value: 2 },
    { text: "Incapable de soulever une plume", value: 1 },
  ],

  agilitéLevels: [
    { text: "Agilité divine", value: 10 },
    { text: "Agilité surnaturelle", value: 9 },
    { text: "Réflexes ultra-rapides", value: 8 },
    { text: "Réflexes impressionnants", value: 7 },
    { text: "Très agile", value: 6 },
    { text: "Agile", value: 5 },
    { text: "Moyenne", value: 4 },
    { text: "Un peu gauche", value: 3 },
    { text: "Lent dans les mouvements", value: 2 },
    { text: "Un pied gauche", value: 1 },
  ],

  enduranceLevels: [
    { text: "Endurance légendaire", value: 10 },
    { text: "Endurance infinie", value: 9 },
    { text: "Endurance surhumaine", value: 8 },
    { text: "Endurance extrême", value: 7 },
    { text: "Très endurant", value: 6 },
    { text: "Endurant", value: 5 },
    { text: "Moyenne", value: 4 },
    { text: "Peu endurant", value: 3 },
    { text: "Fatigue rapide", value: 2 },
    { text: "S'essouffle en montant des escaliers", value: 1 },
  ],

  charismeLevels: [
    { text: "Charisme divin", value: 10 },
    { text: "Charisme irrésistible", value: 9 },
    { text: "Charisme magnétique", value: 8 },
    { text: "Charisme exceptionnel", value: 7 },
    { text: "Très charismatique", value: 6 },
    { text: "Charismatique", value: 5 },
    { text: "Moyen", value: 4 },
    { text: "Manque de charisme", value: 3 },
    { text: "Difficile à écouter", value: 2 },
    { text: "Présence inexistante", value: 1 },
  ],

  visionLevels: [
    { text: "Vision divine", value: 10 },
    { text: "Vision surhumaine", value: 9 },
    { text: "Vision parfaite", value: 8 },
    { text: "Vision exceptionnelle", value: 7 },
    { text: "Vision aiguisée", value: 6 },
    { text: "Vision normale", value: 5 },
    { text: "Vision moyenne", value: 4 },
    { text: "Vision floue", value: 3 },
    { text: "Vision très floue", value: 2 },
    { text: "Quasi-aveugle sans lunettes", value: 1 },
  ],

  perceptionLevels: [
    { text: "Perception utlime", value: 10 },
    { text: "Perception omnisciente", value: 9 },
    { text: "Perception ultra-développée", value: 8 },
    { text: "Perception affinée", value: 7 },
    { text: "Très perceptif", value: 6 },
    { text: "Perceptif", value: 5 },
    { text: "Moyenne", value: 4 },
    { text: "Peu perceptif", value: 3 },
    { text: "Ne remarque pas l'évidence", value: 2 },
    { text: "Ne détecte même pas les bruits autour de soi", value: 1 },
  ],

  résistanceLevels: [
    { text: "Résistance absolue", value: 10 },
    { text: "Résistance surhumaine", value: 9 },
    { text: "Très résistant", value: 8 },
    { text: "Résistant", value: 7 },
    { text: "Moyenne", value: 6 },
    { text: "bonne résistance", value: 5 },
    { text: "Faible résistance", value: 4 },
    { text: "Très faible résistance", value: 3 },
    { text: "Fragile", value: 2 },
    { text: "Brisé par une brise légère", value: 1 },
  ],
};

export const hakiLevels = [
    { level: "Haki des Rois", probability: 1 },
    { level: "Haki de l'Armement", probability: 20 },
    { level: "Haki de l'Observation", probability: 40 },
    { level: "aucun haki", probability: 69 },
  ];

export const genre = [
    { level: "Homme", probability: 85 },
    { level: "Femme", probability: 15 },
  ];